apiVersion: cert-manager.io/v1alpha2
kind: Issuer
metadata:
  name: letsencrypt-issuer-prod
spec:
  acme:
    email: skyglass2001@gmail.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-issuer-prod-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
